### ISSUE TITLE
If I edit (change colors, smooth, contrast, sharpen, shadows, or face editing big nose, change smile) or change to JPG and reduce the file size, the cloaked images are still valid?

### ISSUE THREAD

**Issue by panderlad** [Shawn-Shan/fawkes#117]
I cloaked an jpg image of 500kb and the cloaked image is PNG 2500kb.

A lot of difference in file size.

If I reduce the file size and change to jpg, the cloaking will still be valid or will lose it's qualities?

And if i do some image editing?

thanks

**Comment by MarkSCQ** [comment]
From my understandings of the paper, when the input(one image) gets fed to the Fawkes, it will do several things, and they are: 
1. Use MTCNN to cropped face and then use feature extractor to preprocess the image(face), all the images in the system need to be cropped from origin images, and get preprocessed by the feature extractor; 
2. Select target class and the selection is mainly based on l2 distance, Euclidean distance. Fawkes will randomly pick X target classes and finally set the one whose distance is the largest as the target class; 
3. After getting the target class, use the DSSIM value as constraint to solve an optimization problem to get the ideal cloaking.
4. Merging the cloaking with origin image(output).

Since there is a Randomness, obviously, the results will have a very low possibility of being identical. The target class of 500kb and the target of 2500kb could be different just because of randomly picking targets.

Below is my guess about your question from another angle, and I cannot ensure it's correct.
If we are using the same target (without randomness), I think the results might be identical. The face image cropped from origin images will finally be fixed at some sizes like 227*227, 224*224, 64*64, ... and the resizing of images may make images similar, since the images are similar, the difference of fracture vectors might not be that huge
again, I am not familiar with Image Compression,  this is only my guess.

**Comment by panderlad** [comment]
I mean editing the image after the cloaking.

**Comment by MarkSCQ** [comment]
I have no idea. But you can use some online free API(like azure) to see the change of confidence values(before and after). This will help you.

**Comment by emilywenger** [comment]
You can take a look at some of the techniques we tried in our paper: http://people.cs.uchicago.edu/~ravenben/publications/abstracts/fawkes-usenix20.html. TL;DR: compression, noise, and blurring (smoothing) in small amounts do not affect cloak efficacy. However, some of the larger edits you propose (such as changing the nose, etc) would very likely impact cloak efficacy since they change the feature space of the image. I would recommend completing all desired edits *before* cloaking the image.
