### ISSUE TITLE
homebrew binary please 🙏

### ISSUE THREAD

**Issue by joshuaberetta** [Shawn-Shan/fawkes#20]
Please either add a checksum to your website or add to brew repository for mac 😊

**Comment by Shawn-Shan** [comment]
That's a good idea. I will do that when I get the chance.

**Comment by robertpeteuil** [comment]
I was going to post a request to publish this to brew, but I found this issue. 

IMO - brew has an advantage for installing python utilities vs pypy, since it brew keeps all the dependencies separate.  You can also pre-compile as brew bottles for different os’s to speed the install process. 

Here’s an example brew [formula](https://github.com/robpco/homebrew-tap/blob/master/Formula/mcc.rb) for a Python app I wrote a while back.  
A couple notes: 
- if you’re not publishing ‘bottles’ you can leave out that section.  
- since your app is mainstream it can likely be submitted to the official brew formula repo. (Whereas I put mine on my own tap.)
