### ISSUE TITLE
cloak not working?

### ISSUE THREAD

**Issue by JSheadache** [Shawn-Shan/fawkes#36]
Thank you for your efforts and research in this area.

I tried cloaking images with Fawkes default settings. When I try it against Amazon rekognition demos the cloak has little to no effect. What am I doing wrong?

e.g.

Celebrity recognition demo, download Bezos sample image, run fawkes, upload cloaked image - recognition match is still 100%

face comparison demo: uploaded original, and cloaked image - match was 99.9%

**Comment by Shawn-Shan** [comment]
Yes, our cloak might not work if you simply compare the similarity. 

Fawkes is designed to defeat large scale face recognition models (in the similarity matching case there are only two class, you or not you). So in order to test, you need to use the face verification API, upload your own image + many images of other people, use the API to train model, and check whether your original image will be recognized as you. 

This is fairly complicated, we are actively working on a simple code base to help you test it.

**Comment by JSheadache** [comment]
Thank you very much for your reply.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
