### ISSUE TITLE
Very bad work with female face

### ISSUE THREAD

**Issue by LiskFox** [Shawn-Shan/fawkes#72]
Hello, when I use female photo with you program, it creates very **ugly** results. How I can change your male photos dataset to female photos dataset? Thank you!

**Comment by tredondo** [comment]
The default setting worked fine on my wife's photo. Unless you think she's **ugly**. In which case we have a problem.

![20191016_121204_min_cloaked](https://user-images.githubusercontent.com/10043369/91004796-0b890c80-e58a-11ea-81a0-ec1ce5005cb6.jpg)

**Comment by LiskFox** [comment]
Whats command options you are use? In my case it creates ugly results, maybe I doing something wrong..

**Comment by LiskFox** [comment]
> The default setting worked fine on my wife's photo. Unless you think she's **ugly**. In which case we have a problem.
> 
> ![20191016_121204_min_cloaked](https://user-images.githubusercontent.com/10043369/91004796-0b890c80-e58a-11ea-81a0-ec1ce5005cb6.jpg)

Whats command options you are use? In my case it creates ugly results, maybe I doing something wrong..

**Comment by tredondo** [comment]
@LiskFox: why did you quote my entire message including the photo?

I didn't use any special options, just the `-d ./`.

**Comment by emjoywill** [comment]
@LiskFox I assume that by "ugly" you mean that the cloak perturbations are very visible. The visibility of the perturbation depends more on the content of the original image rather than the gender of the individual in question. We have found that highly edited images (i.e. skin artificially smoothed) result in more visible perturbations, since the algorithm struggles finds more "natural" features to change for the cloak.

**Comment by veb** [comment]
@LiskFox instead of perhaps annoying everyone, you could post these "ugly" photos so we know what we're looking at and @emjoywill will understand better. Just a helpful tip.
