### ISSUE TITLE
when cloaked, still get detected by chinese site as follows

### ISSUE THREAD

**Issue by zerospaceeee** [Shawn-Shan/fawkes#85]
Result:

**https://www.faceplusplus.com.cn/face-detection/**

**Comment by emjoywill** [comment]
Yes, this is because Fawkes is designed to protect you against _future_ models trained on your cloaked images, not existing models (like Face++) that already are potentially trained on your uncloaked images. Testing on an existing Face++ model will not tell you if Fawkes works. You can find more details about how we performed real-world tests of Fawkes in our paper.
