### ISSUE TITLE
Mac gui not masking!

### ISSUE THREAD

**Issue by EmmiBevensee** [Shawn-Shan/fawkes#87]
Hey I ran the min setting on CLI and on Mac GUI and the mac version is seemingly completely unperterbed compared to the CLI min setting. Also a nice way to test these is running them against pimeyes. I found that min did not work but low did on the picture. I also wonder if someday some of the masks that do general noise instead of like making my image look like i got beat up will be possibly because the final result of high is pretty terrifying haha! 

thanks for building this so i didn't have to! good job!

**Comment by emjoywill** [comment]
Did you actually do a diff between the two images to check that the cloaking didn't work? The goal of the cloak is to be imperceptible to human eyes, so not being able to see it is no proof that the cloak failed. 

While pimeyes is an interesting tool, it can't actually (afaik) test the efficacy of Fawkes, since it looks like you just upload photos and try pimeyes tries to match it to other photos of you. Fawkes is meant to prevent _new_ models trained on the cloaked images from recognizing you. Fawkes isn't designed to fool _existing_ models (like pimeyes). The fact that Fawkes can defeat pimeyes is more a commentary on the weakness of that model rather than the strength of Fawkes. 

We are actively working on ways to improve Fawkes. :) Thanks!
