### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.15.0

### ISSUE THREAD

**Issue by shepard127** [Shawn-Shan/fawkes#89]
During installation fawkes requires tensorflow 1.15.0

![image](https://user-images.githubusercontent.com/20435233/94898635-8a7f3800-049a-11eb-9ca1-7c4755755084.png)

I am trying to install Tensorflow of this version but nothing works

![image](https://user-images.githubusercontent.com/20435233/94899157-7425ac00-049b-11eb-8a9c-9c33db9b87b2.png)

P.S.
I'm using x64 python version 3

**Comment by MoralCode** [comment]
i was able to  get `pip3 install .` (with a `git clone`-d version of fawkes) to work on my system by using a version of python thats less than 3.8 (i used https://github.com/pyenv/pyenv to do that, and also pipenv for good measure). My system is running essentially a stock Kubuntu and I currently have `Python 3.8.5` installed system-wide, however, using `pyenv` i was able to make it use version `3.7.9` and so far the install has made it to the "Downloading tensorflow-1.15.0[bunch of other stuff]" stage without error.

I think i came to this conclusion due to a different error i saw (dont remember the command that produced it, but the error was `ERROR: Package 'fawkes' requires a different Python: 3.8.5 not in '>=3.5,<3.8'` (suspect i got that from manually removing one of the two limits on the tensorlow version in the `setup.py`)

**Comment by muckisg** [comment]
I have some problems on versions aswell. Is there a chance to get a requirements.txt via pip freeze? It would make the installation much more conforbale i guess.

**Comment by g-w1** [comment]
try python 3.7

**Comment by Shawn-Shan** [comment]
We do not support python 3.8, please downgrade python to run the code.
